# Generated by Django 2.1.1 on 2018-09-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miti', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('in_time', models.CharField(blank=True, max_length=100, null=True)),
                ('out_time', models.CharField(blank=True, max_length=100, null=True)),
                ('punch_count', models.IntegerField(blank=True, null=True)),
                ('time_spent', models.FloatField(blank=True, null=True)),
                ('difference_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AttendanceRecord',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Employee'),
        ),
    ]
