# Generated by Django 2.1.1 on 2018-09-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180913_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='emp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
