# Generated by Django 2.1.1 on 2018-09-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20180913_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
