# Generated by Django 2.1.1 on 2018-09-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20180914_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='emp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.Employee'),
            preserve_default=False,
        ),
    ]
