# Generated by Django 2.1.1 on 2018-09-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20180914_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='emp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
